services:
  - type: web
    name: baseball-app
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    envVars:
      - key: DatabaseType
        value: PostgreSQL
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
