// <auto-generated />
using System;
using BaseballApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaseballApp.Migrations
{
    [DbContext(typeof(BaseballDbContext))]
    partial class BaseballDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("BaseballApp.Models.Batter", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("playerId");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("playerName");

                    b.HasKey("PlayerId");

                    b.ToTable("tblBatter", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.BatterBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AB");

                    b.Property<int>("BB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BB");

                    b.Property<int>("CS")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CS");

                    b.Property<int>("DP")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DP");

                    b.Property<int>("E")
                        .HasColumnType("INTEGER")
                        .HasColumnName("E");

                    b.Property<int>("GIDP")
                        .HasColumnType("INTEGER")
                        .HasColumnName("GIDP");

                    b.Property<int>("GameSeq")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gameSeq");

                    b.Property<int>("H")
                        .HasColumnType("INTEGER")
                        .HasColumnName("H");

                    b.Property<int>("HBP")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HBP");

                    b.Property<int>("HR")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HR");

                    b.Property<string>("HomeOrAway")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("homeOrAway");

                    b.Property<int>("IBB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IBB");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order");

                    b.Property<int>("PA")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PA");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("playerId");

                    b.Property<int>("R")
                        .HasColumnType("INTEGER")
                        .HasColumnName("R");

                    b.Property<int>("RBI")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RBI");

                    b.Property<int>("SB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SB");

                    b.Property<int>("SF")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SF");

                    b.Property<int>("SH")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SH");

                    b.Property<int>("SO")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SO");

                    b.Property<string>("SeasonId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("seasonId");

                    b.Property<int>("SubOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("subOrder");

                    b.Property<int>("TP")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TP");

                    b.Property<int>("ThreeB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("3B");

                    b.Property<int>("TwoB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("2B");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId", "GameSeq");

                    b.ToTable("tblBatterBox", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.BattingRankingCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ab");

                    b.Property<decimal>("AVG")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("avg");

                    b.Property<int>("BB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bb");

                    b.Property<int>("Games")
                        .HasColumnType("INTEGER")
                        .HasColumnName("games");

                    b.Property<int>("H")
                        .HasColumnType("INTEGER")
                        .HasColumnName("h");

                    b.Property<int>("HBP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HR")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hr");

                    b.Property<decimal>("OBP")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("obp");

                    b.Property<decimal>("OPS")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("ops");

                    b.Property<int>("PA")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pa");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("playerId");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("playerName");

                    b.Property<int>("R")
                        .HasColumnType("INTEGER")
                        .HasColumnName("r");

                    b.Property<int>("RBI")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rbi");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rank");

                    b.Property<int>("SB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sb");

                    b.Property<int>("SF")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SLG")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("slg");

                    b.Property<int>("SO")
                        .HasColumnType("INTEGER")
                        .HasColumnName("so");

                    b.Property<string>("SeasonId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("seasonId");

                    b.Property<int>("ThreeB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("threeB");

                    b.Property<int>("TwoB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("twoB");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "PlayerId")
                        .IsUnique();

                    b.HasIndex("SeasonId", "Rank");

                    b.ToTable("tblBattingRankingCache", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.Codes.CodeBases", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("tblCodeBases", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.Codes.CodeEventType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("tblCodeEventType", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.Codes.CodeHardness", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("tblCodeHardness", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.Codes.CodePitchCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("tblCodePitchCode", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.Codes.CodePitchType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("tblCodePitchType", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.Codes.CodeResult", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("tblCodeResult", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.Codes.CodeRunnerType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("tblCodeRunnerType", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.Codes.CodeTrajectory", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("tblCodeTrajectory", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BatterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CatcherId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CoordX")
                        .HasColumnType("TEXT")
                        .HasColumnName("coordX");

                    b.Property<decimal?>("CoordY")
                        .HasColumnType("TEXT")
                        .HasColumnName("coordY");

                    b.Property<bool>("InPlay")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBall")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStrike")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("paId");

                    b.Property<string>("PitchCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("pitchCode");

                    b.Property<string>("PitchType")
                        .HasColumnType("TEXT")
                        .HasColumnName("pitchType");

                    b.Property<string>("PitcherId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Velocity")
                        .HasColumnType("TEXT")
                        .HasColumnName("velocity");

                    b.HasKey("Id");

                    b.HasIndex("BatterId");

                    b.HasIndex("CatcherId");

                    b.HasIndex("PAId");

                    b.HasIndex("PaId");

                    b.HasIndex("PitcherId");

                    b.ToTable("tblEvent", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.Game", b =>
                {
                    b.Property<string>("SeasonId")
                        .HasColumnType("TEXT")
                        .HasColumnName("seasonId");

                    b.Property<int>("Seq")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seq");

                    b.Property<string>("AwayTeamId")
                        .HasColumnType("TEXT")
                        .HasColumnName("awayTeamId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("HomeTeamId")
                        .HasColumnType("TEXT")
                        .HasColumnName("homeTeamId");

                    b.Property<int?>("StadiumId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stadiumId");

                    b.HasKey("SeasonId", "Seq");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("StadiumId");

                    b.ToTable("tblGame", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.PA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AwayScores")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Balls")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Bases")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bases");

                    b.Property<string>("BatterHand")
                        .HasColumnType("TEXT");

                    b.Property<string>("BatterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("batterId");

                    b.Property<string>("CatcherId")
                        .HasColumnType("TEXT")
                        .HasColumnName("catcherId");

                    b.Property<int?>("EndAwayScores")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndBases")
                        .HasColumnType("INTEGER")
                        .HasColumnName("endBases");

                    b.Property<int?>("EndHomeScores")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndOuts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameSeq")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gameSeq");

                    b.Property<string>("Hardness")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeOrAway")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("homeOrAway");

                    b.Property<int?>("HomeScores")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("HomeWE")
                        .HasColumnType("TEXT");

                    b.Property<int>("Inning")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inning");

                    b.Property<bool>("IsPH")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationCode")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Outs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaRound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaSeq")
                        .HasColumnType("INTEGER")
                        .HasColumnName("paSeq");

                    b.Property<string>("PitcherHand")
                        .HasColumnType("TEXT");

                    b.Property<string>("PitcherId")
                        .HasColumnType("TEXT")
                        .HasColumnName("pitcherId");

                    b.Property<int?>("RBI")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RE")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RE24")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Scored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeasonId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("seasonId");

                    b.Property<int?>("Strikes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trajectory")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WPA")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BatterId");

                    b.HasIndex("CatcherId");

                    b.HasIndex("PitcherId");

                    b.HasIndex("SeasonId", "GameSeq");

                    b.ToTable("tblPA", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.Pitcher", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("playerId");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("playerName");

                    b.HasKey("PlayerId");

                    b.ToTable("tblPitcher", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.PitcherBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("BB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BB");

                    b.Property<int?>("BF")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BF");

                    b.Property<int?>("ER")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ER");

                    b.Property<int>("GameSeq")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gameSeq");

                    b.Property<int?>("H")
                        .HasColumnType("INTEGER")
                        .HasColumnName("H");

                    b.Property<int?>("HB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HB");

                    b.Property<int?>("HR")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HR");

                    b.Property<string>("HomeOrAway")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("homeOrAway");

                    b.Property<int?>("IBB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IBB");

                    b.Property<int?>("IPOuts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IPOuts");

                    b.Property<int?>("NP")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NP");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order");

                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("playerId");

                    b.Property<int?>("R")
                        .HasColumnType("INTEGER")
                        .HasColumnName("R");

                    b.Property<int?>("SO")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SO");

                    b.Property<string>("SeasonId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("seasonId");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId", "GameSeq");

                    b.ToTable("tblPitcherBox", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.PitchingRankingCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("BAA")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("baa");

                    b.Property<int>("BB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bb");

                    b.Property<decimal>("BB9")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("bb9");

                    b.Property<int>("ER")
                        .HasColumnType("INTEGER")
                        .HasColumnName("er");

                    b.Property<decimal>("ERA")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("era");

                    b.Property<int>("Games")
                        .HasColumnType("INTEGER")
                        .HasColumnName("games");

                    b.Property<int>("H")
                        .HasColumnType("INTEGER")
                        .HasColumnName("h");

                    b.Property<int>("HR")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hr");

                    b.Property<decimal>("IP")
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("ip");

                    b.Property<int>("IPOuts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ipOuts");

                    b.Property<decimal>("K9")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("k9");

                    b.Property<decimal>("KBBRatio")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("kbbRatio");

                    b.Property<int>("L")
                        .HasColumnType("INTEGER")
                        .HasColumnName("l");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("playerId");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("playerName");

                    b.Property<int>("R")
                        .HasColumnType("INTEGER")
                        .HasColumnName("r");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rank");

                    b.Property<int>("SO")
                        .HasColumnType("INTEGER")
                        .HasColumnName("so");

                    b.Property<string>("SeasonId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("seasonId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.Property<int>("W")
                        .HasColumnType("INTEGER")
                        .HasColumnName("w");

                    b.Property<decimal>("WHIP")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("whip");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "PlayerId")
                        .IsUnique();

                    b.HasIndex("SeasonId", "Rank");

                    b.ToTable("tblPitchingRankingCache", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.PlayerTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("endDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isActive");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("playerId");

                    b.Property<string>("PlayerNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("playerNumber");

                    b.Property<string>("SeasonId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("seasonId");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("startDate");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("teamId");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId");

                    b.ToTable("tblPlayerTeam", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.Runner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ERPitcherId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsER")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOut")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRBI")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RunnerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("runnerId");

                    b.Property<string>("RunnerPlayerPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Scored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ERPitcherId");

                    b.HasIndex("EventId");

                    b.HasIndex("RunnerPlayerPlayerId");

                    b.ToTable("tblRunner", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.Scores", b =>
                {
                    b.Property<string>("SeasonId")
                        .HasColumnType("TEXT")
                        .HasColumnName("seasonId");

                    b.Property<int>("GameSeq")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gameSeq");

                    b.Property<string>("HomeOrAway")
                        .HasColumnType("TEXT")
                        .HasColumnName("homeOrAway");

                    b.Property<int>("Inning")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inning");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.HasKey("SeasonId", "GameSeq", "HomeOrAway", "Inning");

                    b.ToTable("tblScores", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.Season", b =>
                {
                    b.Property<string>("SeasonId")
                        .HasColumnType("TEXT")
                        .HasColumnName("seasonId");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("season");

                    b.HasKey("SeasonId");

                    b.ToTable("tblSeason", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.Stadium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("stadium")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stadium");

                    b.HasKey("Id");

                    b.ToTable("tblStadium", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.Team", b =>
                {
                    b.Property<string>("TeamId")
                        .HasColumnType("TEXT")
                        .HasColumnName("teamId");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("teamName");

                    b.HasKey("TeamId");

                    b.ToTable("tblTeam", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.TeamGameStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ab");

                    b.Property<int>("BB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bb");

                    b.Property<int>("BbAllowed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bbAllowed");

                    b.Property<int>("CS")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cs");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<int>("ER")
                        .HasColumnType("INTEGER")
                        .HasColumnName("er");

                    b.Property<string>("GameDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("gameDate");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("gameId");

                    b.Property<int>("H")
                        .HasColumnType("INTEGER")
                        .HasColumnName("h");

                    b.Property<int>("HBP")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hbp");

                    b.Property<int>("HR")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hr");

                    b.Property<int>("HitsAllowed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hitsAllowed");

                    b.Property<int>("HrAllowed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hrAllowed");

                    b.Property<int>("IPOuts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ipOuts");

                    b.Property<int>("IsHome")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isHome");

                    b.Property<int>("OpponentScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("opponentScore");

                    b.Property<string>("OpponentTeamId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("opponentTeamId");

                    b.Property<string>("OpponentTeamName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("opponentTeamName");

                    b.Property<int>("PA")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pa");

                    b.Property<int>("SB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sb");

                    b.Property<int>("SF")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sf");

                    b.Property<int>("SO")
                        .HasColumnType("INTEGER")
                        .HasColumnName("so");

                    b.Property<string>("SeasonId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("seasonId");

                    b.Property<int>("SoPitching")
                        .HasColumnType("INTEGER")
                        .HasColumnName("soPitching");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("teamId");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("teamName");

                    b.Property<int>("TeamScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("teamScore");

                    b.Property<int>("ThreeB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("threeB");

                    b.Property<int>("TwoB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("twoB");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "TeamId")
                        .IsUnique();

                    b.ToTable("tblTeamGameStats", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.TeamSeasonRankingCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ab");

                    b.Property<decimal>("AVG")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("avg");

                    b.Property<int>("BB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bb");

                    b.Property<int>("CS")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cs");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("gamesPlayed");

                    b.Property<int>("H")
                        .HasColumnType("INTEGER")
                        .HasColumnName("h");

                    b.Property<int>("HBP")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hbp");

                    b.Property<int>("HR")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hr");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER")
                        .HasColumnName("losses");

                    b.Property<decimal>("OBP")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("obp");

                    b.Property<decimal>("OPS")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("ops");

                    b.Property<int>("PA")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pa");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rank");

                    b.Property<int>("RunsAllowed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("runsAllowed");

                    b.Property<int>("RunsScored")
                        .HasColumnType("INTEGER")
                        .HasColumnName("runsScored");

                    b.Property<int>("SB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sb");

                    b.Property<int>("SF")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sf");

                    b.Property<decimal>("SLG")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("slg");

                    b.Property<int>("SO")
                        .HasColumnType("INTEGER")
                        .HasColumnName("so");

                    b.Property<string>("SeasonId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("seasonId");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("teamId");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("teamName");

                    b.Property<int>("ThreeB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("threeB");

                    b.Property<int>("TwoB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("twoB");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wins");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "Rank");

                    b.HasIndex("SeasonId", "TeamId");

                    b.ToTable("tblTeamSeasonRankingCache", (string)null);
                });

            modelBuilder.Entity("BaseballApp.Models.BatterBox", b =>
                {
                    b.HasOne("BaseballApp.Models.Batter", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseballApp.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("SeasonId", "GameSeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BaseballApp.Models.Event", b =>
                {
                    b.HasOne("BaseballApp.Models.Batter", "Batter")
                        .WithMany()
                        .HasForeignKey("BatterId");

                    b.HasOne("BaseballApp.Models.Batter", "Catcher")
                        .WithMany()
                        .HasForeignKey("CatcherId");

                    b.HasOne("BaseballApp.Models.PA", "PA")
                        .WithMany()
                        .HasForeignKey("PAId");

                    b.HasOne("BaseballApp.Models.PA", null)
                        .WithMany()
                        .HasForeignKey("PaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseballApp.Models.Pitcher", "Pitcher")
                        .WithMany()
                        .HasForeignKey("PitcherId");

                    b.Navigation("Batter");

                    b.Navigation("Catcher");

                    b.Navigation("PA");

                    b.Navigation("Pitcher");
                });

            modelBuilder.Entity("BaseballApp.Models.Game", b =>
                {
                    b.HasOne("BaseballApp.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BaseballApp.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BaseballApp.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseballApp.Models.Stadium", "Stadium")
                        .WithMany()
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Season");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("BaseballApp.Models.PA", b =>
                {
                    b.HasOne("BaseballApp.Models.Batter", "Batter")
                        .WithMany()
                        .HasForeignKey("BatterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BaseballApp.Models.Batter", "Catcher")
                        .WithMany()
                        .HasForeignKey("CatcherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BaseballApp.Models.Pitcher", "Pitcher")
                        .WithMany()
                        .HasForeignKey("PitcherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BaseballApp.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("SeasonId", "GameSeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batter");

                    b.Navigation("Catcher");

                    b.Navigation("Game");

                    b.Navigation("Pitcher");
                });

            modelBuilder.Entity("BaseballApp.Models.PitcherBox", b =>
                {
                    b.HasOne("BaseballApp.Models.Pitcher", "Pitcher")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BaseballApp.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("SeasonId", "GameSeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Pitcher");
                });

            modelBuilder.Entity("BaseballApp.Models.PlayerTeam", b =>
                {
                    b.HasOne("BaseballApp.Models.Batter", "Batter")
                        .WithMany("PlayerTeams")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseballApp.Models.Pitcher", "Pitcher")
                        .WithMany("PlayerTeams")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseballApp.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseballApp.Models.Team", "Team")
                        .WithMany("PlayerTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batter");

                    b.Navigation("Pitcher");

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BaseballApp.Models.Runner", b =>
                {
                    b.HasOne("BaseballApp.Models.Pitcher", "ERPitcher")
                        .WithMany()
                        .HasForeignKey("ERPitcherId");

                    b.HasOne("BaseballApp.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseballApp.Models.Batter", "RunnerPlayer")
                        .WithMany()
                        .HasForeignKey("RunnerPlayerPlayerId");

                    b.Navigation("ERPitcher");

                    b.Navigation("Event");

                    b.Navigation("RunnerPlayer");
                });

            modelBuilder.Entity("BaseballApp.Models.Scores", b =>
                {
                    b.HasOne("BaseballApp.Models.Game", "Game")
                        .WithMany("Scores")
                        .HasForeignKey("SeasonId", "GameSeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("BaseballApp.Models.Batter", b =>
                {
                    b.Navigation("PlayerTeams");
                });

            modelBuilder.Entity("BaseballApp.Models.Game", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("BaseballApp.Models.Pitcher", b =>
                {
                    b.Navigation("PlayerTeams");
                });

            modelBuilder.Entity("BaseballApp.Models.Team", b =>
                {
                    b.Navigation("PlayerTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
